### ISSUE TITLE
Chapter 1 working thread

### ISSUE THREAD

**Issue by hupili** [hupili/python-for-data-and-media-communication-gitbook#2]
https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-01.md

Tick when resolved:

* [x] https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-01.md#how-to-open-terminal-on-mac  . Add a screenshot to show spotlight search result.
* [x] https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-01.md#2-shell-commands  . Add one screenshot of an entire Terminal to show multiple commands and their input/ output
* [x] https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-01.md#2-shell-commands . Use markdown "block code" notation to demo the input/ output of commands, **instead of** screenshots (images). This way looks better and also allows readers to copy and paste.
* [x] https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-01.md#2-shell-commands  Please explain the components of the interactions in shell. That is, what is the `$`? the username / path before `$`? The user's input and the shell's output. Think of the questions that first time readers would ask. Use this screenshot, plus some annotations, to explain in details.
* [x] Please turn them those pointers into URLs. "*(If it doesn't work, you can download some third party editors,such as **sublime**, **visual studio code**. You can edit .py file by these editors.)*"
* [x] Rename the screenshot files to readable filename, i.e. a [slug-style](https://en.wikipedia.org/wiki/Clean_URL) filename. Do not simply use the default "Screenshot ..." name. Or we will lose track in the future. 
* [x] Markdown Lint

----

Use the following thread for discussion.

**Comment by hupili** [comment]
It looks better to take screenshot of an entire window. See here: https://support.apple.com/en-us/HT201361

**Comment by hupili** [comment]
Watch out for privacy when taking screenshots. You may want to mask some personal information.

**Comment by hupili** [comment]
@ChicoXYC , I made full review and added some more content requirements. Please study my modifications [here](https://github.com/hupili/python-for-data-and-media-communication-gitbook/commit/035beea9b5d7c8525a58b25a89355e922280cb9f) for a better convention of using markdown. Notable points:

* **command+S** -->  **Command+s** . If you use "S", that usually means shift+s, aka capital. **command+S** is equivalent to **Command+Shift+s**
* Insert blanks around section headers
* Do not leave HTML codes in markdown file unless necessary.

**Comment by hupili** [comment]
Please use VSCode for offline editing and preview. The side panel is from an extension called "Markdown Preview Enhanced". This is more efficient than modifying on GitHub web UI. 

<img width="1552" alt="screen shot 2018-07-22 at 9 14 51 am" src="https://user-images.githubusercontent.com/1227160/43041333-b52d0ffc-8d8f-11e8-88db-6eb1e8c69e99.png">

**Comment by bonnie-yu** [comment]
<ul>
<li>Should also advise the meaning of "pwd" in the directory part.</li>
<li>Can change "cd python, cd to a certain folder" to "cd XX, XX refers to any certain folder in the directory". Starters always tend to follow the instructions tightly so will be better to give clear instructions. File names python can be misunderstood as the python installation package.</li>
<li>typo whther-->whether
<img width="957" alt="screen shot 2018-07-25 at 9 01 36 pm" src="https://user-images.githubusercontent.com/35587764/43197335-36aad616-904e-11e8-8b81-096ce5a52929.png"></li>
<li>The command to execute .py file should be explained in detail. The path before $ is not clearly stated.
<img width="682" alt="screen shot 2018-07-25 at 9 08 32 pm" src="https://user-images.githubusercontent.com/35587764/43197640-226c1c72-904f-11e8-8cec-0b2771501a36.png">
</li>
</ul>

**Comment by ChicoXYC** [comment]
@bonnie-yu @hupili thanks for your feedback! I will modify soon.

**Comment by bonnie-yu** [comment]
Should advise 1) the suggested python version, 2) how to use the command “python v” to check python version,  3) method to make Python 2.7 and Python 3 coexist in the very beginning of chapter 1. So learners don’t need to get back to these fundamentals in the half of learning.

**Comment by hupili** [comment]
@ChicoXYC please install the markdown lint plugin to help conform to the convention.

<img width="956" alt="screen shot 2018-07-28 at 8 57 12 pm" src="https://user-images.githubusercontent.com/1227160/43356729-d8968b9e-92a8-11e8-9950-81930deb6604.png">

non-conventional use will be highlighted as follows:

<img width="569" alt="screen shot 2018-07-28 at 8 56 08 pm" src="https://user-images.githubusercontent.com/1227160/43356730-daa2eb9e-92a8-11e8-8836-42f1fdd18c47.png">

Although the current version has no problem rendering on GitHub, it may have problem in other markdown parsers/ renderers. It is good practice to follow the convention, so your code works everywhere.

**Comment by ChicoXYC** [comment]
@hupili Thx for your help. updated!

**Comment by hupili** [comment]
Well done.
